module.exports.ERROR_CODE_SERVER_ERROR = 500;
module.exports.ERROR_CODE_BAD_REQUEST = 400;
module.exports.ERROR_CODE_NOT_FOUND = 404;
module.exports.ERROR_CODE_UNAUTHORIZED_ERROR = 401;
module.exports.ERROR_CODE_CONFLICT_ERROR = 409;
